name: Fetch Team GitHub Stats

on:
  workflow_dispatch:
    inputs:
      team:
        description: "Team"
        required: true
        default: "k8s_team"
        options:
          - k8s_team
          - obs_team
          - db_team
      from_date:
        description: "From date (yyyy-mm-dd)"
        required: true
      to_date:
        description: "To date (yyyy-mm-dd)"
        required: true

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script to gather github stats
        run: python src/fetch_stats.py
        env:
          TEAM_NAME: ${{ github.event.inputs.team }}
          FROM_DATE: ${{ github.event.inputs.from_date }}
          TO_DATE: ${{ github.event.inputs.to_date }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
